const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const source=fs.readFileSync(require('node:path').join(__dirname,'../auth-provider.js'),'utf8');
function storage(seed={}) {const data=new Map(Object.entries(seed));return {data,getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k)};}
function setup(local=storage({excedereProjectTasks:'["Keep exactly"]',excedereProjectTasksBackupV1:'original',unrelated:'keep'}),session=storage()) {const window={};vm.runInNewContext(source,{window,localStorage:local,sessionStorage:session});return {auth:window.ExcedereAuth,local,session};}
test('session-only sign-in survives reload but not a new independent session',async()=>{const {auth,local,session}=setup();await auth.signIn({email:'test@example.com',password:'projects-demo',remember:false});assert.ok(await setup(local,session).auth.getSession());assert.equal(await setup(local).auth.getSession(),null);});
test('remember me survives a fresh session and sign-out preserves every project and unrelated value',async()=>{const {auth,local,session}=setup();const original=[...local.data];await auth.signIn({email:'test@example.com',password:'projects-demo',remember:true});assert.ok(await setup(local).auth.getSession());assert.equal(session.data.size,0);await auth.signOut();assert.deepEqual([...local.data],original);assert.equal(await auth.getSession(),null);});
test('email and password are never stored and auth is excluded from project backups',async()=>{const {auth,local,session}=setup();await auth.signIn({email:'private@example.com',password:'projects-demo',remember:true});const saved=JSON.stringify([...local.data,...session.data]);assert.ok(!saved.includes('private@example.com'));assert.ok(!saved.includes('projects-demo'));assert.ok(!auth.key.startsWith('excedere'));});
test('invalid password and malformed sessions do not grant entry or mutate data',async()=>{const {auth,local}=setup();const before=[...local.data];await assert.rejects(auth.signIn({email:'test@example.com',password:'wrong',remember:true}));assert.deepEqual([...local.data],before);for(const raw of ['{broken','null','{}','{"version":1,"mode":"real"}']){local.setItem(auth.key,raw);assert.equal(await auth.getSession(),null);}});
test('switching remembered sign-in off removes previous remembered session',async()=>{const {auth,local,session}=setup();await auth.signIn({email:'test@example.com',password:'projects-demo',remember:true});await auth.signIn({email:'test@example.com',password:'projects-demo',remember:false});assert.equal(local.getItem(auth.key),null);assert.ok(session.getItem(auth.key));});
test('storage write failure is reported without changing project data',async()=>{const {auth,local}=setup();const before=[...local.data];local.setItem=()=>{throw Error('Quota exceeded')};await assert.rejects(auth.signIn({email:'test@example.com',password:'projects-demo',remember:true}),/could not save/);assert.deepEqual([...local.data],before);});
test('password recovery explains demo and does not change stored data',async()=>{const {auth,local}=setup();const before=[...local.data];assert.match(await auth.requestPasswordReset(),/No account or reset email/);assert.deepEqual([...local.data],before);});
